// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB84uGqLc_qLHuUPb3dF7oAcugBO5dM60E',
    appId: '1:653060127190:web:4c8297bb90441e11078c77',
    messagingSenderId: '653060127190',
    projectId: 'fir-helper-c5a43',
    authDomain: 'fir-helper-c5a43.firebaseapp.com',
    storageBucket: 'fir-helper-c5a43.appspot.com',
    measurementId: 'G-7ESFFMJKXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJdKLHA7ClBDy0-3jrgU3Uh2hljlluQP0',
    appId: '1:653060127190:android:8e8e2240932578a4078c77',
    messagingSenderId: '653060127190',
    projectId: 'fir-helper-c5a43',
    storageBucket: 'fir-helper-c5a43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2tKeNnCs1DWlJqdxaoVwzFA1ZfIM_zS8',
    appId: '1:653060127190:ios:1bc01b6ad6b8406d078c77',
    messagingSenderId: '653060127190',
    projectId: 'fir-helper-c5a43',
    storageBucket: 'fir-helper-c5a43.appspot.com',
    iosBundleId: 'com.example.firebaseHelper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2tKeNnCs1DWlJqdxaoVwzFA1ZfIM_zS8',
    appId: '1:653060127190:ios:1bc01b6ad6b8406d078c77',
    messagingSenderId: '653060127190',
    projectId: 'fir-helper-c5a43',
    storageBucket: 'fir-helper-c5a43.appspot.com',
    iosBundleId: 'com.example.firebaseHelper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB84uGqLc_qLHuUPb3dF7oAcugBO5dM60E',
    appId: '1:653060127190:web:4e2cea27744d85d4078c77',
    messagingSenderId: '653060127190',
    projectId: 'fir-helper-c5a43',
    authDomain: 'fir-helper-c5a43.firebaseapp.com',
    storageBucket: 'fir-helper-c5a43.appspot.com',
    measurementId: 'G-NPHS4YW1Q9',
  );
}
